name: flutter_firebase_auth_test_app
description: Reusable firebase auth widgets
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.1 <3.3.3"
  flutter: ">=1.17.0"

dependencies:
  firebase_core: ^2.3.0
  cloud_firestore: ^4.0.1
  firebase_auth_web: 5.1.3
  firebase_auth: 4.1.5
  firebase_storage: ^11.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  gap: ^2.0.0
  flutter_svg: ^1.1.6
  common:
    git: 
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: common
  sandbox:
    git: 
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: sandbox
  providers:
    git: 
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: providers
  auth:
    git: 
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: auth
  widgets:
    git: 
      url: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
      path: widgets
  # flutter_firebase_framework:
  #   git: https://github.com/Super-Fast-Forward/flutter_firebase_framework.git
dependency_overrides:
  common:
    path: ../flutter_firebase_framework/common
  providers:
    path: ../flutter_firebase_framework/providers
  auth:
    path: ../flutter_firebase_framework/auth


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # assets:
  #   - assets/


